// Generates data/lore.js from analysis/lore_raw/*.json (Qwen bulk drafts,
// Claude taste-passed). Codex/act prose mirrors LORE.md (canon source — if you
// edit LORE.md sections, re-mirror here). Run: node tools/gen_lore_data.js
import { readdirSync, readFileSync, writeFileSync } from 'fs';

const RAW = 'analysis/lore_raw';
const OUT = 'data/lore.js';

const units = {};
for (const f of readdirSync(RAW).filter(f => f.endsWith('.json'))) {
  const o = JSON.parse(readFileSync(`${RAW}/${f}`, 'utf8'));
  units[o.type] = {
    lean: o.lean,
    epigraph: o.epigraph.trim(),
    vignette: o.vignette.trim(),
    note: (o.codex_note || '').trim(),
  };
}

const codices = {
  verdant: {
    title: 'Codex Viridis — the Verdant',
    text: 'A reality where life perfected itself into permanence. Forests of glass and gold; growth that keeps everything it makes. A Verdant city is a single tree grown patient for ten thousand years. Its people did not defeat death; they out-remembered it. War doctrine: keep everything, forget nothing, grow until the question of victory answers itself. Its anchor in Limen is the palace-tree.',
  },
  umbral: {
    title: 'Codex Cineris — the Umbral',
    text: 'A reality of ember and obsidian: appetite and transformation. Its cities burn what they were to become what they will be, lit forever by their own spending. Nothing is wasted and nothing is kept. Its people do not mourn; they kindle. War doctrine: spend everything, waste nothing, become whatever wins. Its anchor in Limen is the ember spire.',
  },
  rift: {
    title: 'Codex Liminis — the between',
    text: 'Where the realities met, both failed: the Rift, a seam where nothing stays true, leaking motes of raw possibility. Some things were born in it and are fed by it. The threshold-folk lived at the crossing before either world noticed; their masonry serves both sides, because when only one world survives, you want your work remembered in it.',
  },
  war: {
    title: 'On the Inscription War',
    text: 'Nothing fights and nothing dies. Ground believes, or stops believing. Conquest buries: the conqueror’s truth is written over the old one, which survives underneath, dormant — war strata, fossil arguments. The tower remembers every conqueror. Contested ground rises; deep truth presses down on its neighbors. The ground nearest the Rift decides the war: the wound listens, and every sixth turn it stirs.',
  },
};

const acts = [
  { title: 'Act I — The Meeting', text: 'Before Limen there was no “between.” Then the line. The Verdant felt it as a cold that memory could not keep out. The Umbral felt it as a fire that gave no light. Where they touched, both laws failed at once; the Rift tore, the motes bled, and around the wound a country condensed that belonged to neither — hexes of possible ground, waiting to be told what they were.' },
  { title: 'Act II — The Inscription War', text: 'Both worlds sent what they could spare: not armies — arguments. Aspects, inscribed one per heartbeat. The first time a Verdant thicket was unwritten by an ember-runner, both worlds understood: only one of us leaves this place real. The ground began to stack. Chokepoints rose into towers of buried conviction, and the threshold-folk sold their masonry to both sides.' },
  { title: 'Act III — The Listening Ground', text: 'Every campaign converges on the seam, because the seam decides. Veterans say you can hear it: stand beside the Rift and the wound hums with your conviction, doubled. Somewhere ahead is the last inscription — a palace-tree guttering out, an ember spire gone cold, or the day the threshold, patient as ground, simply chooses. Every match is that day.' },
];

const banner = '// GENERATED by tools/gen_lore_data.js — do not hand-edit. Source: analysis/lore_raw/ + LORE.md.';
writeFileSync(OUT, `${banner}
export const LORE = ${JSON.stringify({ codices, acts, units }, null, 1)};
`);
console.log(`wrote ${OUT}: ${Object.keys(units).length} units`);
